### ISSUE TITLE
channelReTau110のplot.pyでindex out of bounds

### ISSUE THREAD

**Issue by aokomoriuta** [opencae/VandV#1]
channelReTau110でplot.pyを実行すると以下のようになりpdfが作成できません。
```
$ ../bin/plot.py
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:91: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:113: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
-1cells-Smagorinsky--1MPI-time
/usr/lib64/python2.7/site-packages/matplotlib/axes.py:2760: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0, top=0.0
  + 'bottom=%s, top=%s') % (bottom, top))
-1cells-Smagorinsky-1MPI-time
-1cells-Smagorinsky-2MPI-time
-1cells-Smagorinsky-4MPI-time
-1cells-Smagorinsky-8MPI-time
-1cells-Smagorinsky-12MPI-time
-1cells-Smagorinsky-16MPI-time
-1cells-laminar--1MPI-time
-1cells-laminar-1MPI-time
Traceback (most recent call last):
  File "../bin/plot.py", line 54, in <module>
    offset=(x[len(x)-1]-x[0])*0.05
IndexError: index out of bounds
```

table.csvは以下のようになっています
https://gist.github.com/aokomoriuta/51bb382070e356a79854

手順がおかしい可能性もあるので、その場合はご指摘下さい。
他に問題解決に必要なファイルがありましたら教えて下さい。

よろしくお願いします。

**Comment by masazzz** [comment]
ありがとうございます．

table.csv をみると，各ベンチマークケースでのソルバのログ

    n_*/mpi_*/simulationType_*/log.*[0-9] 

での計算時間(ExecutionTime)の取得に失敗していますので，
table.sh の問題ですが，そもとも RapidCFD GPUのビルドにまだ成功していなかった
と思いますので，このソルバのログはRapidCFD GPUのソルバ以外のものでしょうか?

以下も見せて頂けますか?

    n_00008/mpi_00001/simulationType_laminar-LESModel_laminar-delta_cubeRootVol-solver_PCG-preconditioner_FDIC/log.*[0-9]

**Comment by aokomoriuta** [comment]
@masazzz 

この結果はOpenFOAM-devのものです（そもそもOpenFAOMを自力でビルドしたことなかったのでその練習で）。

log*は https://gist.github.com/aokomoriuta/747a5519f7ba0631177c になります。
よくみたら"FOAM FATAL IO ERROR"となってますね・・・そもそも計算できてなかったってことでしょうか。

**Comment by masazzz** [comment]
これで如何でしょうか?

https://github.com/opencae/VandV/commit/a8b8ab453dc20348508560abfdc5808920c1b777

なお，現在他のマシンでのベンチマークは全て OpenFOAM-2.3.0 で行っていますし，
OpenFOAM-dev では動作確認をしていないので，お時間がある時に2.3.0でお試しください．

**Comment by masazzz** [comment]
[table.sh](https://github.com/opencae/VandV/blob/master/OpenFOAM/OpenFOAM-BenchmarkTest/channelReTau110/bin/table.sh) ですが，計算が終了していないソルバーのログはskipするようにしました(実は元からそうしていたのですが，バグがありました)．

https://github.com/opencae/VandV/commit/2707cd52d65305165f876fb35757360815d16108

**Comment by aokomoriuta** [comment]
解決してOpenFOAM-devではとりあえず結果が取得できました。
https://bitbucket.org/aokomoriuta/openfoam-result/src/f881539940c1172a5d2c4ad7c46e0f3d82e2f3a1/OpenFOAM-dev/sgm01/?at=master

ありがとうございました。
特に残件なければ本チケット、クローズでお願いします。
